/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tungsten_hmclpe_utils_DigestUtils */

#ifndef _Included_com_tungsten_hmclpe_utils_DigestUtils
#define _Included_com_tungsten_hmclpe_utils_DigestUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tungsten_hmclpe_utils_DigestUtils_STREAM_BUFFER_LENGTH
#define com_tungsten_hmclpe_utils_DigestUtils_STREAM_BUFFER_LENGTH 1024L
#ifdef __cplusplus
}
#endif
#endif
