name: auto build HMCLPE - Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
    # 在push tag时触发
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: cd HMCLPE&&../gradlew build
    #step：上传apk 到action，在右上角查看
    # 官方文档 https://help.github.com/cn/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifactst
    - name: Upload APK to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HMCLPE-release-selfsigned.apk
        path: HMCLPE/build/outputs/apk/release/HMCLPE-release.apk
        asset_content_type: application/apk
    - name: Upload and share APK to lanzoucloud
      run: python UploadLZY.py '${{ secrets.lanzou_cookie }}'

